2025-02-21 08:37:42.537 ERROR (MainThread) [homeassistant.helpers.intent] Service call failed for assist_satellite.my_satellite
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 1118, in async_handle_states
    await service_coro
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 634, in _wait_for_one
    return f.result() if resolve else f
           ~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/intent/__init__.py", line 227, in async_call_service
    raise intent.IntentHandleError(
        f"Service {service} does not support entity {state.entity_id}"
    )
homeassistant.helpers.intent.IntentHandleError: Service turn_off does not support entity assist_satellite.my_satellite
