2025-02-20 12:09:51.888 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration n8n_conversation_agent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-20 12:09:52.335 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2025-02-20 12:09:52.354 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=95 from 2025-02-20 12:07:45.764943)
2025-02-20 12:09:53.809 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'n8n_conversation_agent' accesses hass.components.conversation, which should be updated to import functions used from conversation directly at custom_components/n8n_conversation_agent/__init__.py, line 22: hass.components.conversation.async_set_agent(hass, agent). This will stop working in Home Assistant 2025.3, please report it to the author of the 'n8n_conversation_agent' custom integration
2025-02-20 12:09:53.809 ERROR (MainThread) [homeassistant.setup] Error during setup of component n8n_conversation_agent: 'HomeAssistant' object has no attribute 'entry_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 422, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/n8n_conversation_agent/__init__.py", line 22, in async_setup
    hass.components.conversation.async_set_agent(hass, agent)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/__init__.py", line 125, in async_set_agent
    get_agent_manager(hass).async_set_agent(config_entry.entry_id, agent)
                                            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HomeAssistant' object has no attribute 'entry_id'
